import time

def answer(input, str1, str2):
    if input == 'y': print(str1)
    elif input == 'n': print(str2)
    else: print('Please enter either y or n')

print ('You are at work. You received a sunflower with a note on your desk.')
time.sleep(2)
print('What would you do now?')
time.sleep(2)
ans = input('Press y + Enter to read the note.\n' + 'Press n + Enter to toss the note.\n')
answer(ans, 'Hi. I hope you have a spendid day, like a sunflower.', 'You toss the note.')
time.sleep(2)
print("You decide to get some coffee from the break room.")
time.sleep(2)
print('While you are pouring coffee, you notice Ask is looking at you.')
time.sleep(2)
print('Ash has dark hair, good-looking face, dresses minimalistic, and drinks coffee every 3 hours.')
time.sleep(3)
print('You ask yourself if you should investigate.')
time.sleep(2)
ans = input('Press y + Enter to investigate.\n'+'Press n + Enter to do nothing.\n')
answer(ans, 'You: Hey Ash, this seems like out of nowhere but what is your favorite flower?', 'You ignore the investigation.')
time.sleep(2)
if ans == "y":
    print('Ask: Hi, uhm, I like margaret.')
    time.sleep(1.5)
    print('You concluded they are not your Secret Admirer.')
time.sleep(2)
print('You got out of break room.')
time.sleep(2)
print('Minh says hi to you. Minh is everyone favorite coworker. They have beautiful black hair, tall, tan skin and they love everything about fishes.')
time.sleep(3)
print('Minh invites you to eat lunch with them.')
print('During lunch, you ask what is their favorite type of flower.')
time.sleep(2)
ans = input('Press y + Enter to ask.\n'+'Press n + Enter to do nothing.\n')
time.sleep(2)
answer(ans, "Minh: I actually don't like flowers, but I love fish", 'You stay absolutely quiet.')
time.sleep(2)
if ans == "y": print('You realize Minh is not your Secret Admirer.')
else: print('You enjoy looking at the floating cloud while you eat lunch with your coworker.')
time.sleep(2)
print('After a day of working, you decide to stay at the office a little longer to finish work.')
time.sleep(2)
print('You notice Vas is also working late. Vas has dyed blue hair, they have so many indoor plants on their desk, and they wear headphones 99% of the time.')
time.sleep(4)
print('You kinda like them because they helped you fix the printer last week.')
time.sleep(2)
print('It would be nice if they are your Secret Admirer.')
time.sleep(2)
ans = input('Press y + Enter to gather courage to ask them.\n'+'Press n + Enter to chicken out.\n')
time.sleep(2)
answer(ans, "You: Uhm, hey Vas, I know we don't talk but since you have so many plants, what is your favorite flower?", 'You chicken out, too scare to ask them.')
time.sleep(2)
if ans == 'y':
    print('Vas stays idle because they have their headphones on.')
    time.sleep(2)
    print('You ask again, a little louder this time.')
    time.sleep(2)
    print('Vas turns around, take their headphones off. Vas blushes a little bit because you are too close.')
    time.sleep(3)
    print('Vas says s..sunflower.')
    time.sleep(1)
    print('You blush too. Vas is your Secret Admirer.')
    time.sleep(1)
    print('Vas asks if you want to do go dinner with them.')
    time.sleep(2)
    print('You say yes. You and Vas both smile while packing stuff to leave the office for a dinner date.')
    time.sleep(2)
    print('THE END <3')
else:
    print('Since you finish work, you pack your stuff and ready leave the office.')
    time.sleep(2)
    print('You think Vas was glancing at you but you do not care, you are thinking about dinner.')
    time.sleep(2)
    print('THE END')
